[WIP] criado o modelo para o gtfs
prefeitura-rio/queries-rj-smtr pull request #122
Opened 2023-10-05 21:12 UTC by lingsv

## Changelog
- Descrição das mudanças, idealmente em tópicos por modelo ou conjunto de alterações

## Checklist

- [ ] Já testei os modelos no BigQuery
- [ ] Já existe pipeline no Prefect
- [ ] Título do PR está 💯

> Utilize os seguintes padrões de nomeação:
> 
> 1. Alterações em modelos: `[smtr][pipeline/dataset sem prefixo*] <fix/feat>: <descricao>`
> 2. Alterações no repositório: `[smtr][infra] <fix/feat>: <descricao>`
>
> \* Ex: br_rj_riodejaneiro_onibus_gps -> onibus_gps

2023-10-19 17:55 UTC, eng-rodrigocunha requested changes

2023-10-19 17:55 UTC, eng-rodrigocunha commented on models/br_rj_riodejaneiro_gtfs/agency_gtfs.sql
> +  SAFE_CAST(data AS DATE) data,
Trocar `data` por `data_versao` em todas as tabelas

2023-10-19 17:55 UTC, eng-rodrigocunha commented on models/br_rj_riodejaneiro_gtfs/calendar_dates_gtfs.sql
> +    SAFE_CAST(JSON_VALUE(content, '$.monday') AS STRING) monday,
Corrigir demais campos

2023-10-19 17:55 UTC, eng-rodrigocunha commented on models/br_rj_riodejaneiro_gtfs/fare_attributes_gtfs.sql
> +    SAFE_CAST(JSON_VALUE(content, '$.currency_type') AS FLOAT64) currency_type,
Corrigir tipo

2023-10-19 17:55 UTC, eng-rodrigocunha commented on models/br_rj_riodejaneiro_gtfs/fare_attributes_gtfs.sql
> +    SAFE_CAST(JSON_VALUE(content, '$.payment_method') AS FLOAT64) payment_method,
Corrigir tipo

2023-10-19 17:55 UTC, eng-rodrigocunha commented on models/br_rj_riodejaneiro_gtfs/fare_rules_gtfs.sql
> +    SAFE_CAST(JSON_VALUE(content, '$.fare_id') AS STRING) fare_id,
Corrigir estrutura

2023-10-19 17:55 UTC, eng-rodrigocunha commented on models/br_rj_riodejaneiro_gtfs/feed_info_gtfs.sql
> +    SAFE_CAST(JSON_VALUE(content, '$.feed_start_date') AS DATE) feed_start_date,
Datas estão no padrão?

2023-10-19 17:55 UTC, eng-rodrigocunha commented on models/br_rj_riodejaneiro_gtfs/frequencies_gtfs.sql
> +       SAFE_CAST(start_time AS DATETIME) start_time,
Corrigir tipo e aprimorar tratamento para horários > 24h para `start_time` e `end_time`

2023-10-19 17:55 UTC, eng-rodrigocunha commented on models/br_rj_riodejaneiro_gtfs/frequencies_gtfs.sql
> +       SAFE_CAST(JSON_VALUE(content, '$.exact_times') AS DATETIME) exact_times,
Corrigir tipo

2023-10-19 17:55 UTC, eng-rodrigocunha commented on models/br_rj_riodejaneiro_gtfs/ordem_servico_gtfs.sql
> +{{ config(
materializar

2023-10-19 17:55 UTC, eng-rodrigocunha commented on models/br_rj_riodejaneiro_gtfs/agency_gtfs.sql
> +  materialized = 'incremental',
como o modelo já é incremental, não precisa repetir em todas as tabelas

2023-10-19 17:55 UTC, eng-rodrigocunha commented on models/br_rj_riodejaneiro_gtfs/ordem_servico_gtfs.sql
> +
Padronizar esta query com as outras ou o contrário

2023-10-19 17:55 UTC, eng-rodrigocunha commented on models/br_rj_riodejaneiro_gtfs/schema.yml
> +        description: "Nome completo da agência de trânsito."
agência de transporte público

2023-10-19 17:55 UTC, eng-rodrigocunha commented on models/br_rj_riodejaneiro_gtfs/shapes_geom_gtfs.sql
> +       	      --CAST(shape_pt_lat AS FLOAT64) shape_pt_lat,
Retirar comentários

2023-10-19 17:55 UTC, eng-rodrigocunha commented on models/br_rj_riodejaneiro_gtfs/stop_times_gtfs.sql
> +    SAFE_CAST(JSON_VALUE(content, '$.departure_time') AS DATETIME) departure_time,
Corrigir tipos

2023-10-19 17:55 UTC, eng-rodrigocunha commented on models/br_rj_riodejaneiro_gtfs/stop_times_gtfs.sql
> +
Inserir demais colunas (inclusive opcionais) e ordená-las conforme documentação

2023-10-19 17:55 UTC, eng-rodrigocunha commented on models/br_rj_riodejaneiro_gtfs/stops_gtfs.sql
> +
Inserir colunas adicionais

2023-10-19 17:55 UTC, eng-rodrigocunha commented on models/br_rj_riodejaneiro_gtfs/trips_gtfs.sql
> +
Incluir colunas adicionais e ordenar conforme documentação

2023-10-20 17:46 UTC, carolkgn commented on models/br_rj_riodejaneiro_gtfs/trips_gtfs.sql
> +
Já está na ordem das colunas do arquivo.

2023-10-20 17:48 UTC, carolkgn commented on models/br_rj_riodejaneiro_gtfs/stops_gtfs.sql
> +
Já está com as colunas e ordem do arquivo.

2023-10-20 17:49 UTC, carolkgn commented on models/br_rj_riodejaneiro_gtfs/stop_times_gtfs.sql
> +
Já está com as colunas e ordem do arquivo.

2023-10-20 18:03 UTC, lingsv commented on dev/run.py
> +# import os
ok.

2023-10-20 23:53 UTC, eng-rodrigocunha approved these changes

2023-10-23 14:37 UTC, closed without merging