Refatorar modelo `veiculo`
prefeitura-rio/queries-rj-smtr pull request #255
Opened 2024-04-08 15:19 UTC by eng-rodrigocunha

Refatorar modelo `veiculo` com base no

2024-04-08 19:59 UTC, vtr363 commented
# Alterações
- Refatora o modelo veiculo separando em view na subpasta staging e a referenciando na tabela final

2024-04-11 18:17 UTC, pixuimpou commented on models/veiculo/staging/sppo_registro_agente_verao_staging.sql
`WHERE
  data = (SELECT MAX(data) FROM rj-smtr-staging.veiculo_staging.sppo_registro_agente_verao)
  AND SAFE_CAST(JSON_VALUE(content,'$.validacao') AS BOOL) = TRUE`
  retirar filtro
  recriar tabela materializada fora do staging e botar esse filtro nela

2024-04-11 18:17 UTC, pixuimpou commented on models/veiculo/staging/sppo_vistoria_tr_subtt_cglf_2023.sql
colocar _staging

2024-04-11 18:17 UTC, pixuimpou commented on models/veiculo/staging/sppo_vistoria_tr_subtt_cglf_pendentes_2024.sql
colocar _staging

2024-04-11 18:17 UTC, pixuimpou commented on models/veiculo/staging/sppo_vistoria_tr_subtt_cglf_2024.sql
colocar _staging

2024-04-11 19:53 UTC, pixuimpou requested changes

2024-04-11 19:53 UTC, pixuimpou commented on models/veiculo/sppo_veiculo_dia.sql
> -      {{ ref("sppo_registro_agente_verao") }}
manter sppo_registro_agente_verao

2024-04-15 15:06 UTC, pixuimpou requested changes

2024-04-15 15:06 UTC, pixuimpou commented on models/veiculo/staging/schema.yml
> +    description: "sppo_vistoria_tr_subtt_cglf_2023"
adicionar _staging

2024-04-15 15:06 UTC, pixuimpou commented on models/veiculo/staging/schema.yml
> +  - name: sppo_vistoria_tr_subtt_cglf_2024
adicionar _staging

2024-04-15 15:06 UTC, pixuimpou commented on models/veiculo/staging/schema.yml
> +    description: "sppo_vistoria_tr_subtt_cglf_2024"
Adicionar _staging

2024-04-15 15:06 UTC, pixuimpou commented on models/veiculo/sppo_registro_agente_verao.sql
> +  {% set ultimaDataAgenteVerão = run_query("SELECT MAX(data) FROM " ~ ref('sppo_registro_agente_verao_staging'))[0][0] %}
a gente não usa variável camelcase nem com acento

2024-04-15 17:38 UTC, pixuimpou requested changes

2024-04-15 17:38 UTC, pixuimpou commented on models/veiculo/CHANGELOG.md
> +## [1.0.2] - 2024-04-15
alterar para 1.1.0

2024-04-15 18:29 UTC, pixuimpou approved these changes

2024-04-15 20:07 UTC, merged