[Subsídio SPPO v6][feature] Trajetos alternativos
prefeitura-rio/queries-rj-smtr pull request #261
Opened 2024-04-09 19:54 UTC by eng-rodrigocunha

## Changelog
- Inclui nova feature de trajetos alternativos

2024-04-12 20:22 UTC, pixuimpou requested changes

2024-04-12 20:22 UTC, pixuimpou commented on models/gtfs/ordem_servico_trips_shapes_gtfs2.sql
> +  trips AS (
essa parte do trips e trips alternativo não da pra usar a mesma CTE, usando a regra dos filtros como sendo uma coluna que indica se é alternativo ou não?

2024-04-12 20:22 UTC, pixuimpou commented on models/gtfs/ordem_servico_trips_shapes_gtfs2.sql
> +        CASE
acredito que os cases no where podem ser trocados por OR.
exemplo:
(o.tipo_dia = t.tipo_dia OR o.tipo_dia = "Ponto Facultativo" AND t.tipo_dia = "Dia Útil" )

2024-04-12 20:22 UTC, pixuimpou commented on models/gtfs/ordem_servico_trips_shapes_gtfs2.sql
> +    shape_id AS shape_id_planejado,
Esse tratamento da CTE ordem_servico_trips_shapes, pode ser feito na de cima ordem_servico_trips

2024-04-12 20:22 UTC, pixuimpou commented on models/gtfs/ordem_servico_trips_shapes_gtfs2.sql
> +  ordem_servico_tipo_dia AS (
os UNPIVOTs podem voltar pra ordem_servico_gtfs2, ja que não precisam de nenhum join

2024-04-13 00:19 UTC, eng-rodrigocunha commented on models/gtfs/ordem_servico_trips_shapes_gtfs2.sql
> +  trips AS (
O `PARTITION BY` usa colunas diferentes, mas é possível inserir na mesma CTE com um `UNION ALL` e adicionar uma coluna de indicador

2024-04-15 21:32 UTC, eng-rodrigocunha commented on models/projeto_subsidio_sppo/viagem_planejada.sql
> +    data BETWEEN DATE_SUB("{{ var('run_date') }}", INTERVAL 1 DAY) AND DATE("{{ var('run_date') }}") )
Apenas para data atual

2024-04-15 21:32 UTC, eng-rodrigocunha commented on models/gtfs/ordem_servico_trips_shapes_gtfs2.sql
> +        AND t.trip_headsign LIKE CONCAT("%", ot.evento, "%")
Ajustar service_id EXCEP

2024-04-19 12:59 UTC, pixuimpou approved these changes

2024-04-19 13:01 UTC, merged