[smtr][gtfs] Criar tabela `shapes_with_stops` no GTFS
prefeitura-rio/queries-rj-smtr pull request #57
Opened 2023-01-13 20:04 UTC by yxuo

## Motivo
Entendeu-se que é interessante criar a tabela e copiar para o banco de dados do servidor mobilidade-rio-api, pois esta consulta demora 20 minutos ou mais para renderizar. O servidor irá consultar os dados prontos direto do banco, economizando tempo.

## Changelog
- README: Copiar de `dev/profiles-example.yml` para `profiles-dev/profiles.yml`, seguindo o padrão usado em [profiles.yml ](https://github.com/prefeitura-rio/queries-rj-smtr/blob/staging/smtr-add-gtfs/profiles.yml)(da pasta raiz)
- Modelo e `schema.yml` de shapes_with_stops
- gitignore - ignorar arquivos de log `.cpython` e pastas sensíveis como `credentials-dev` e `profiles-dev`..

## Checklist

- [x] Testar os modelos no BigQuery
- [x] Testar os modelos no dbt
- [x] Validar alterações
- [ ] Criar pipeline no Prefect (será feito após o PR)

2023-01-13 20:31 UTC, fernandascovino commented on models/gtfs/shapes_with_stops.sql
> +            JOIN {{ var('trips_staging') }} trips ON (SAFE_CAST(trips.trip_id AS STRING) = stoptimes.trip_id AND stoptimes.timestamp_captura BETWEEN '2022-12-27 10:00:00-03:00' AND '2022-12-27 11:00:
esses dados ja estao tipados nas tabelas desse mesmo diretorio, basta referenciar elas

ex: `{{ ref('trips') }}`

2023-01-13 20:32 UTC, fernandascovino commented on README.md
> +cp dev/profiles-example.yml profiles-dev/profiles.yml
por que tem uma nova pasta?

2023-01-13 20:32 UTC, fernandascovino commented on .gitignore
> +profiles*/
por que tem esses ignores?

2023-01-13 20:33 UTC, fernandascovino commented on models/gtfs/shapes_with_stops.sql
> +            JOIN {{ var('trips_staging') }} trips ON (SAFE_CAST(trips.trip_id AS STRING) = stoptimes.trip_id AND stoptimes.timestamp_captura BETWEEN '2022-12-27 10:00:00-03:00' AND '2022-12-27 11:00:
trocar todas as vars por refs aqui, e remover os casts

2023-01-13 20:39 UTC, fernandascovino requested changes
- Para rodar em dev, não é necessário que se crie nenhuma pasta além da que já existe `dev/`. É só adicionar o  arquivo profiles.yml nessa pasta, que ja sera ignorado, e rodar conforme o readme
 - As tabelas que devem ser puxadas em shapes_with_stops são as views que estao nesse mesmo dataset (gtfs), que ja estao tipadas, e nao as tabelas em staging

2023-01-13 20:40 UTC, fernandascovino commented on .gitignore
> +profiles*/
remover essa mudanca

2023-01-13 20:42 UTC, yxuo commented on README.md
> +cp dev/profiles-example.yml profiles-dev/profiles.yml
Esta nova pasta é usada pelo `/dev/utils.py` e `/dev/run.py` por padrão pada executar o dbt de teste.

Esta pasta também é usada pelo `/profiles.yml` (na pasta raiz do repo)

2023-01-13 21:53 UTC, yxuo commented on README.md
> +cp dev/profiles-example.yml profiles-dev/profiles.yml
Pelos motivos explicados abaixo, estas mudanças devem e serão removidas.

2023-01-13 22:05 UTC, yxuo commented
Alterações no README e .gitignore referentes às pastas `/profiles-dev` e `credentials-dev` foram desfeitas conforme discutido.

2023-01-13 22:15 UTC, yxuo commented on models/gtfs/shapes_with_stops.sql
> +            JOIN {{ var('trips_staging') }} trips ON (SAFE_CAST(trips.trip_id AS STRING) = stoptimes.trip_id AND stoptimes.timestamp_captura BETWEEN '2022-12-27 10:00:00-03:00' AND '2022-12-27 11:00:
> trocar todas as vars por refs aqui, e remover os casts

Primeiro os `var()` serão trocados por refs nas linhas indicadas.

Em seguida todos os `SAFE_CAST()` serão removidos enquanto a query ou o dbt não apresentarem erros de formatação.

Caso algum `SAFE_QUEST()` seja essencial para impedir erros, será relatado neste PR.

2023-01-18 14:32 UTC, yxuo commented
## O que será feito esta semana (18/01/2022 - 20/01/2022):
- [ ] Retirar o `SAFE_CAST` de variáveis no sql, desde que não altere o resultado da query.
  > **Caso que ocorreu nessa query:** ordenar por `stop_sequence`, que foi considerado `string ` ao invés de `int`.  
  > **Conclusão:** 18/01/2022
- [ ] Trocar, no DBT, o uso de `var()` por `ref()` das tabelas em models.gtfs

### ⚠️ Não dê merge ainda, há tarefas extras abaixo:
- [ ] Revisar a query, testando se as _subqueries_ obtém o resultado esperado
  > **Conclusão:** 19/01/2022
- [ ] Validar a query de forma apropriada (pode ser necessário elaborar um critério de validação)
  > **Conclusão:** 20/01/2022

**Motivo das tarefas extras:**

A falta de validação eficaz levanta dúvidas se esta query trás o resultado desejado.

**Por que isto não foi feito antes?**

O principal motivo foi o critério insuficientemente eficaz de validação usado nesta query.

2023-06-20 17:06 UTC, fernandascovino commented
Dados não serão mais adicionados no BQ

2023-06-20 17:06 UTC, closed without merging